# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['spotify2media.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('ffmpeg/ffmpeg.exe', 'ffmpeg'),
        ('yt-dlp/yt-dlp.exe', 'yt-dlp'),
        ('config.json', '.'),
        ('icon.ico', '.'),
    ],
    hiddenimports=[
        'mutagen',
        'mutagen.easyid3',
        'mutagen.mp4',
        'mutagen.id3',
        'tkinterdnd2',
        'selenium',
        'selenium.webdriver',
        'selenium.webdriver.chrome.service',
        'webdriver_manager',
        'webdriver_manager.chrome',
        'bs4',
        'requests',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Spotify2MP3',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['icon.ico'],
)
